; Generated by AutoGUI 2.6.2
#SingleInstance Force
#NoEnv
SetWorkingDir %A_ScriptDir%
SetBatchLines -1

Gui Font, s12, Segoe UI
Gui Add, Text, x16 y24 w70 h23 +0x200, 類型：
Gui Add, Picture, x240 y0 w176 h81, Z:\pic\ad-abstract.png
Gui Add, Picture, x416 y0 w149 h82, Z:\pic\ad-info.png
Gui Add, Picture, x88 y88 w150 h78, Z:\pic\ad-tip.png
Gui Add, Picture, x240 y88 w174 h77, Z:\pic\ad-success.png
Gui Add, Picture, x419 y86 w151 h75, Z:\pic\ad-question.png
Gui Add, Picture, x240 y168 w172 h75, Z:\pic\ad-failure.png
Gui Add, Picture, x421 y169 w144 h73, Z:\pic\ad-danger.png
Gui Add, Picture, x88 y248 w143 h76, Z:\pic\ad-bug.png
Gui Add, Picture, x240 y248 w175 h76, Z:\pic\ad-example.png
Gui Add, Picture, x419 y248 w147 h74, Z:\pic\ad-quote.png
Gui Add, Picture, x88 y168 w150 h76, Z:\pic\ad-warning.png
Gui Add, Picture, x87 y6 w151 h76, Z:\pic\ad-note.png

Gui Show, x474 y140 w594 h348, Admonition 提醒區塊

OnMessage(0x201, "OnWM_LBUTTONDOWN")
Return

AdNote(CtrlHwnd, GuiEvent, EventInfo, ErrLevel := "") {

}

GuiEscape:
GuiClose:
  ExitApp

OnWM_LBUTTONDOWN(wParam, lParam, msg, hWnd) {

}
